#!/usr/bin/env bash
# prove_and_verify.sh – Generate a PLONK proof and verify it locally
#
# Reads input.json (generated by the aggregator), computes the witness,
# generates a PLONK proof, and verifies it with snarkjs.
#
# Prerequisites: run build_setup.sh first
# Usage: cd zk && bash prove_and_verify.sh

set -e
trap 'echo "[ZeroSync ZK] ERROR on line $LINENO. See above for details." >&2' ERR

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

BUILD_DIR="$SCRIPT_DIR/build"
INPUT_FILE="$SCRIPT_DIR/input.json"

echo "============================================="
echo " ZeroSync – ZK Prove & Verify (PLONK)"
echo "============================================="

# ── Check prerequisites ─────────────────────────────────────────────
if [ ! -f "$BUILD_DIR/weighted_sum_js/weighted_sum.wasm" ]; then
  echo "[ZeroSync ZK] ERROR: Circuit WASM not found. Run build_setup.sh first."
  echo "  Fix: npm run zk:setup"
  exit 1
fi

if [ ! -f "$BUILD_DIR/weighted_sum_final.zkey" ]; then
  echo "[ZeroSync ZK] ERROR: ZKey not found. Run build_setup.sh first."
  echo "  Fix: npm run zk:setup"
  exit 1
fi

if [ ! -f "$INPUT_FILE" ]; then
  echo "[ZeroSync ZK] ERROR: input.json not found. Run the aggregator first."
  echo "  Fix: npm run aggregate"
  exit 1
fi

echo ""
echo "Input file: $INPUT_FILE"
cat "$INPUT_FILE"
echo ""

# ── Step 1: Compute witness ──────────────────────────────────────────
echo "[Step 1/3] Computing witness..."
node "$BUILD_DIR/weighted_sum_js/generate_witness.js" \
  "$BUILD_DIR/weighted_sum_js/weighted_sum.wasm" \
  "$INPUT_FILE" \
  "$BUILD_DIR/witness.wtns"
echo "  ✓ Witness: $BUILD_DIR/witness.wtns"

# ── Step 2: Generate PLONK proof ────────────────────────────────────
echo ""
echo "[Step 2/3] Generating PLONK proof..."
snarkjs plonk prove \
  "$BUILD_DIR/weighted_sum_final.zkey" \
  "$BUILD_DIR/witness.wtns" \
  "$BUILD_DIR/proof.json" \
  "$BUILD_DIR/public.json"
echo "  ✓ Proof:   $BUILD_DIR/proof.json"
echo "  ✓ Public:  $BUILD_DIR/public.json"

# ── Step 3: Verify proof ────────────────────────────────────────────
echo ""
echo "[Step 3/3] Verifying proof..."
VERIFY_RESULT=$(snarkjs plonk verify \
  "$BUILD_DIR/verification_key.json" \
  "$BUILD_DIR/public.json" \
  "$BUILD_DIR/proof.json")

echo "  Verification result: $VERIFY_RESULT"

if echo "$VERIFY_RESULT" | grep -qi "OK\|valid\|true"; then
  echo ""
  echo "============================================="
  echo " ✓ PROOF VERIFIED SUCCESSFULLY"
  echo "============================================="
  echo ""
  echo "The aggregator correctly computed the weighted sum."
  echo "Proof artifact: $BUILD_DIR/proof.json"
  echo ""
  echo "Next step: Deploy to Hardhat and publish proof"
  echo "  npm run hardhat:start  (in one terminal)"
  echo "  npm run hardhat:deploy (in another terminal)"
  exit 0
else
  echo ""
  echo "============================================="
  echo " ✗ PROOF VERIFICATION FAILED"
  echo "============================================="
  echo "  Check input.json values and re-run the aggregator."
  exit 1
fi
